Repository src-d/sourced-ui, pull requests merged in 2019-07, with the labels that each got.

#139 Branding typography
  srcd/superset/assets/src/uast/codemirror_override.less
  srcd/superset/assets/src/uast/override.less
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-Black.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-BlackIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-Bold.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-BoldIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-ExtraLight.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-ExtraLightIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-It.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-Light.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-LightIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-Medium.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-MediumIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-Regular.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-Semibold.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceCodePro-SemiboldIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-Black.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-BlackIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-Bold.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-BoldIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-ExtraLight.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-ExtraLightIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-It.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-Light.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-LightIt.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-Regular.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-Semibold.otf.woff2
  srcd/superset/assets/stylesheets/fonts/SourceSansPro-SemiboldIt.otf.woff2
  srcd/superset/assets/stylesheets/less/custom-brand.less
Labels: enhancement, typography

#187 Increase files missing chart height
  srcd/dashboards/gitbase/overview.json
Labels: bug, typography

#142 Adds UI Elements Branding to UI
  srcd/superset/assets/stylesheets/less/custom-brand.less
Labels: enhancement

#196 Typography fixes for merged Branding PR's
  srcd/superset/assets/src/uast/override.less
  srcd/superset/assets/stylesheets/less/custom-brand.less
Labels: bug

#204 This adds branding to the UAST Lab
  srcd/superset/assets/src/uast/override.less
Labels: enhancement

#210 Fix hidden x-scrollbar
  srcd/superset/assets/stylesheets/less/custom-brand.less
Labels: bug

#221 Development environment with hot reloading
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  README.md
  srcd/contrib/docker/docker-compose.override.yml
  srcd/superset/superset_config_dev.py
  superset/contrib/docker/docker-entrypoint.sh
  superset/contrib/docker/docker-init.sh
  watcher
Labels: enhancement
